name: Build & Deploy Astro with Cache

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      page_url: ${{ steps.deploy.outputs.page_url }}
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js + npm cache
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # 3️⃣ Cache .astro e node_modules
      - name: Cache Astro build
        uses: actions/cache@v3
        with:
          path: |
            .astro
            node_modules
          key: ${{ runner.os }}-astro-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-astro-

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 5️⃣ Build site
      - name: Build site
        run: npm run build

      # 6️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
